"""
Data models for the Dataset Validator.

These classes contain only data and no validation logic.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


# ==========================================================
# Per-class statistics
# ==========================================================

@dataclass(slots=True)
class ClassStatistics:
    """
    Statistics for one gesture class.
    """

    gesture: str

    image_count: int = 0

    landmark_rows: int = 0

    metadata_rows: int = 0


# ==========================================================
# Validation Issue
# ==========================================================

@dataclass(slots=True)
class ValidationIssue:
    """
    One validation warning or error.
    """

    severity: str           # INFO | WARNING | ERROR

    message: str

    path: Path | None = None


# ==========================================================
# Validation Report
# ==========================================================

@dataclass(slots=True)
class ValidationReport:
    """
    Final report generated by the validator.
    """

    # Dataset location
    dataset_root: Path

    # Totals
    total_images: int = 0

    total_landmark_rows: int = 0

    total_metadata_rows: int = 0

    corrupted_images: int = 0

    unreadable_images: int = 0

    missing_landmark_files: int = 0

    missing_metadata: bool = False

    stale_metadata_rows: int = 0

    # Final result
    passed: bool = True

    # Detailed statistics
    classes: list[ClassStatistics] = field(
        default_factory=list
    )

    # Validation issues
    issues: list[ValidationIssue] = field(
        default_factory=list
    )

    # ------------------------------------------------------
    # Convenience helpers
    # ------------------------------------------------------

    def add_issue(
        self,
        severity: str,
        message: str,
        path: Path | None = None,
    ) -> None:

        self.issues.append(

            ValidationIssue(
                severity=severity,
                message=message,
                path=path,
            )

        )

        if severity == "ERROR":
            self.passed = False

    def add_class(
        self,
        gesture: str,
    ) -> ClassStatistics:

        stats = ClassStatistics(
            gesture=gesture,
        )

        self.classes.append(stats)

        return stats